# Use the official Node.js image as the base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React app for production
RUN npm run build

#Use a lightweight web server to serve the built app
RUN npm install -g serve

# Expose the port the app will run on
EXPOSE 5173

ENV PORT=5173

# Command to serve the app
CMD ["serve", "-s",  "dist"]